In [9]:
import pandas as pd

# Load the JSON data into a pandas DataFrame
df = pd.read_json('C:/Users/inesm/OneDrive/Documentos/dego-project-team11-TXC/notebooks/raw_credit_applications.json')

# Display the first few rows of the DataFrame
print("DataFrame loaded successfully. First 5 rows:")
df.head()

DataFrame loaded successfully. First 5 rows:

,_id,applicant_info,financials,spending_behavior,decision,processing_timestamp,loan_purpose,notes
0,app_200,"{'full_name': 'Jerry Smith', 'email': 'jerry.s...","{'annual_income': 73000, 'credit_history_month...","[{'category': 'Shopping', 'amount': 480}, {'ca...","{'loan_approved': False, 'rejection_reason': '...",2024-01-15T00:00:00Z,NaN,NaN
1,app_037,"{'full_name': 'Brandon Walker', 'email': 'bran...","{'annual_income': 78000, 'credit_history_month...","[{'category': 'Rent', 'amount': 608}, {'catego...","{'loan_approved': False, 'rejection_reason': '...",NaN,NaN,NaN
2,app_215,"{'full_name': 'Scott Moore', 'email': 'scott.m...","{'annual_income': 61000, 'credit_history_month...","[{'category': 'Rent', 'amount': 109}]","{'loan_approved': True, 'interest_rate': 3.7, ...",NaN,vacation,NaN
3,app_024,"{'full_name': 'Thomas Lee', 'email': 'thomas.l...","{'annual_income': 103000, 'credit_history_mont...","[{'category': 'Fitness', 'amount': 575}]","{'loan_approved': True, 'interest_rate': 4.3, ...",NaN,NaN,NaN
4,app_184,"{'full_name': 'Brian Rodriguez', 'email': 'bri...","{'annual_income': 57000, 'credit_history_month...","[{'category': 'Entertainment', 'amount': 463}]","{'loan_approved': False, 'rejection_reason': '...",2024-01-15T00:00:00Z,NaN,NaN

#### **Understand Data Structure and Alignement**

Inspect the DataFrame's structure using `.info()`, display column names, and confirm the initial data structure with `.head()` to ensure alignment. Get a summary of the columns, their data types, and non-null values. Then, print `df.columns` to list all column names, and finally use `df.head()` to visually confirm the data's initial structure.

In [10]:
print("DataFrame Info:")
df.info()

print("\nDataFrame Columns:")
print(df.columns)

print("\nDataFrame Head:")
df.head()

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 502 entries, 0 to 501
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   _id                   502 non-null    object
 1   applicant_info        502 non-null    object
 2   financials            502 non-null    object
 3   spending_behavior     502 non-null    object
 4   decision              502 non-null    object
 5   processing_timestamp  62 non-null     object
 6   loan_purpose          50 non-null     object
 7   notes                 2 non-null      object
dtypes: object(8)
memory usage: 31.5+ KB

DataFrame Columns:
Index(['_id', 'applicant_info', 'financials', 'spending_behavior', 'decision',
       'processing_timestamp', 'loan_purpose', 'notes'],
      dtype='object')

DataFrame Head:

,_id,applicant_info,financials,spending_behavior,decision,processing_timestamp,loan_purpose,notes
0,app_200,"{'full_name': 'Jerry Smith', 'email': 'jerry.s...","{'annual_income': 73000, 'credit_history_month...","[{'category': 'Shopping', 'amount': 480}, {'ca...","{'loan_approved': False, 'rejection_reason': '...",2024-01-15T00:00:00Z,NaN,NaN
1,app_037,"{'full_name': 'Brandon Walker', 'email': 'bran...","{'annual_income': 78000, 'credit_history_month...","[{'category': 'Rent', 'amount': 608}, {'catego...","{'loan_approved': False, 'rejection_reason': '...",NaN,NaN,NaN
2,app_215,"{'full_name': 'Scott Moore', 'email': 'scott.m...","{'annual_income': 61000, 'credit_history_month...","[{'category': 'Rent', 'amount': 109}]","{'loan_approved': True, 'interest_rate': 3.7, ...",NaN,vacation,NaN
3,app_024,"{'full_name': 'Thomas Lee', 'email': 'thomas.l...","{'annual_income': 103000, 'credit_history_mont...","[{'category': 'Fitness', 'amount': 575}]","{'loan_approved': True, 'interest_rate': 4.3, ...",NaN,NaN,NaN
4,app_184,"{'full_name': 'Brian Rodriguez', 'email': 'bri...","{'annual_income': 57000, 'credit_history_month...","[{'category': 'Entertainment', 'amount': 463}]","{'loan_approved': False, 'rejection_reason': '...",2024-01-15T00:00:00Z,NaN,NaN

#### **Analyze Data Distributions**

Generate descriptive statistics for numerical columns and examine unique values and their frequencies for categorical columns after flattening nested JSON data.

Flatten the nested JSON columns (`applicant_info`, `financials`, `decision`) into new columns and then concatenate them with the original DataFrame, dropping the original nested columns. This is the first step in preparing the data for distribution analysis.

In [13]:
applicant_info_df = pd.json_normalize(df['applicant_info'])
financials_df = pd.json_normalize(df['financials'])
decision_df = pd.json_normalize(df['decision'])

# Concatenate the flattened dataframes with the original df and drop the original nested columns
df = pd.concat([df.drop(columns=['applicant_info', 'financials', 'decision']), applicant_info_df, financials_df, decision_df], axis=1)

print("DataFrame after flattening nested columns:")
print(df.head())

KeyError: 'applicant_info'

Next follow the calculations of the total spending for each applicant from the `spending_behavior` column, handling cases where the list might be empty or `NaN`, and store it in a new column named `total_spending`.

In [ ]:
def calculate_total_spending(spending_list):
    if isinstance(spending_list, list):
        return sum(item.get('amount', 0) for item in spending_list)
    return 0

df['total_spending'] = df['spending_behavior'].apply(calculate_total_spending)

print("DataFrame after calculating total spending:")
print(df[['_id', 'spending_behavior', 'total_spending']].head())

DataFrame after calculating total spending:
       _id                                  spending_behavior  total_spending
0  app_200  [{'category': 'Shopping', 'amount': 480}, {'ca...            1517
1  app_037  [{'category': 'Rent', 'amount': 608}, {'catego...             947
2  app_215              [{'category': 'Rent', 'amount': 109}]             109
3  app_024           [{'category': 'Fitness', 'amount': 575}]             575
4  app_184     [{'category': 'Entertainment', 'amount': 463}]             463

A `KeyError`was encountered when attempting to convert the `dob` column to datetime objects using `pd.to_datetime`, to ensure it is in the correct format for any time-based analysis, as per the instructions.

This happened because the `dob` column was not found in the DataFrame. To prevent this error and ensure robust execution, the following steps check if the `dob` column exists. If it does, it proceeds with converting it to datetime objects. If it does not exist, a warning message indicating that the column is missing and skip the conversion is logged, allowing subsequent steps to proceed without error.

In [14]:
if 'dob' in df.columns:
    df['dob'] = pd.to_datetime(df['dob'], errors='coerce')

    print("DataFrame after converting 'dob' to datetime:")
    print(df[['_id', 'dob']].head())
else:
    print("Warning: 'dob' column not found in DataFrame. Skipping datetime conversion for 'dob'.")
    print("Current DataFrame columns:")
    print(df.columns)

Warning: 'dob' column not found in DataFrame. Skipping datetime conversion for 'dob'.
Current DataFrame columns:
Index(['_id', 'spending_behavior', 'processing_timestamp', 'loan_purpose',
       'notes', 'full_name', 'email', 'ssn', 'ip_address', 'gender',
       'date_of_birth', 'zip_code', 'annual_income', 'credit_history_months',
       'debt_to_income', 'savings_balance', 'annual_salary', 'loan_approved',
       'rejection_reason', 'interest_rate', 'approved_amount',
       'total_spending'],
      dtype='object')